apiVersion: batch/v1
kind: Job
metadata:
  name: nacos-setup-job
  namespace: default
  labels:
    {{- include "nacos.selectorLabels" . | nindent 8 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: nacos-setup-container
          image: cloudapp.tencentcloudcr.com/pkg-2jwz2f6a/nacos-db-init:v8
          imagePullPolicy: IfNotPresent
          # args:
          #   - '99999999'
          # command:
          #   - sleep
          env:
            - name: DB_HOST
              value: {{ .Values.nacos.mysql.host }}
            - name: DB_PORT
              value: "{{ .Values.nacos.mysql.port }}"
            - name: DB_USER
              value: {{ .Values.nacos.mysql.user }}
            - name: DB_PASSWORD
              value: "{{ .Values.nacos.mysql.password }}"
      imagePullSecrets:
        - name: cloudapp-registry-key