kind: Deployment
apiVersion: apps/v1
metadata:
  name: xxl-job-admin
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "xxljob.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xxljob.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.xxljob.image.servicename }}
          image: "{{ .Values.xxljob.image.repository }}/{{ .Values.xxljob.image.project }}/{{ .Values.xxljob.image.servicename }}:{{ .Values.xxljob.image.tag  }}"
          imagePullPolicy: {{ .Values.xxljob.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.xxljob.service.port }}
              protocol: TCP
          env:
            - name: PARAMS
              value: -Dxxl.job.alarmsend= --spring.datasource.url=jdbc:mysql://{{ .Values.global.url }}:{{ .Values.global.port }}/{{ .Values.global.xxl.database }}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai  --spring.datasource.username={{ .Values.global.user }}
                     --spring.datasource.password={{ .Values.global.pass }}
          resources:
            {{- toYaml .Values.xxljob.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data/applogs
              name: xxl-logs
      restartPolicy: Always
      volumes:
        - name: xxl-logs
          persistentVolumeClaim:
            claimName: {{ .Values.xxljob.appsName }}
