apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "xxljob.selectorLabels" . | nindent 4 }}
  name: xxl-job-admin
spec:
  ports:
  - name: http
    port: {{ .Values.xxljob.service.port }}
    nodePort: {{ .Values.xxljob.service.nodePort }}
    protocol: TCP
    targetPort: {{ .Values.xxljob.service.targetPort }}
  selector:
    {{- include "xxljob.selectorLabels" . | nindent 4 }}
  type: {{ .Values.xxljob.service.type }}
