apiVersion: v1
kind: Service
metadata:
  name: digit-paas-private
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: digit-paas-private
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ccn-cncop-hive-gateway
  name: ccn-cncop-hive-gateway
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 2028
  selector:
    app: ccn-cncop-hive-gateway
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sup8-message-center
  name: sup8-message-center
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 2068
  selector:
    app: sup8-message-center
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hive-open-gateway
  name: hive-open-gateway
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 2116
  selector:
    app: hive-open-gateway
  type: ClusterIP

