apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
  name: elasticsearch-master
spec:
  ports:
  - name: http
    port: {{ .Values.elasticsearch.service.http.port }}
    protocol: TCP
    targetPort: {{ .Values.elasticsearch.service.http.targetPort }}
  - name: transport
    port: {{ .Values.elasticsearch.service.transport.port }}
    protocol: TCP
    targetPort: {{ .Values.elasticsearch.service.transport.targetPort }}
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
  name: elasticsearch-master-headless
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: http
    port: {{ .Values.elasticsearch.service.http.port }}
    protocol: TCP
    targetPort: {{ .Values.elasticsearch.service.http.targetPort }}
  - name: transport
    port: {{ .Values.elasticsearch.service.transport.port }}
    protocol: TCP
    targetPort: {{ .Values.elasticsearch.service.transport.targetPort }}
  publishNotReadyAddresses: true
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
  name: np-elasticsearch-master
spec:
  ports:
  - name: http
    port: {{ .Values.elasticsearch.service.http.port }}
    nodePort: {{ .Values.elasticsearch.service.http.nodePort }}
    protocol: TCP
    targetPort: {{ .Values.elasticsearch.service.http.targetPort }}
  - name: transport
    port: {{ .Values.elasticsearch.service.transport.port }}
    nodePort: {{ .Values.elasticsearch.service.transport.nodePort }}
    protocol: TCP
    targetPort: {{ .Values.elasticsearch.service.transport.targetPort }}
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
  type: {{ .Values.elasticsearch.service.type }}
