apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "oapui.selectorLabels" . | nindent 4 }}
  name: skywalking-ui
spec:
  ports:
  - name: page
    port: {{ .Values.oapui.service.port }}
    protocol: TCP
    nodePort: {{ .Values.oapui.service.nodePort }}
    targetPort: {{ .Values.oapui.service.targetPort }}
  selector:
    {{- include "oapui.selectorLabels" . | nindent 4 }}
  type: {{ .Values.oapui.service.type }}
