# 应用 ID，需修改成自己的应用 ID
id: pkg-jtn0an2h

# 自定义安装参数，通过 widget 来声明安装表单获取
args:
  - name: app_zone
    widget: region-and-zone-select
    label: 地域和可用区
    description: 云资源将部署在选择的可用区
    optional: true

  - name: vpc_source
    label: VPC 创建方式
    description: 选择 VPC 的创建方式
    widget: select
    defaultValue: exist
    options:
      - label: 使用现有 VPC
        value: exist
      - label: 创建 VPC
        value: new

  - name: app_target
    label: 安装网络
    widget: subnet-select
    optional: true
    # 支持的地域
    regions:
      - ${app_zone.region}
    when:
      - eq: 
          a: ${vpc_source}
          b: "exist"

  - name: app_sg
    label: 安全组
    widget: security-group-select
    # 支持的地域
    regions:
      - ${app_zone.region}
    optional: true

  - name: app_cvm
    label: cvm 机型
    widget: cvm-instance-type-select
    region: ${app_target.region}
    zone: ${app_target.subnet.zone}
    chargeType: '${charge_type == "PREPAID" ? "PREPAID" : "POSTPAID_BY_HOUR"}'
    incompleteTips: 请先选择安装目标地域

  - name: app_cvm_image
    label: cvm 镜像
    widget: image-select
    region: ${app_target.region}
    instanceType: ${app_cvm.instance_type}
    incompleteTips: 请先选择安装目标地域

  - name: charge_type
    label: 计费类型
    description: 云资源购买使用付费方式
    widget: select
    defaultValue: PREPAID
    options:
      - label: 包年包月
        value: PREPAID
      - label: 按量计费
        value: POSTPAID
    optional: true

  - name: charge_perpaid_period
    label: 购买时长
    widget: input-number
    defaultValue: 1
    description: 云资源包年包月购买的月份数
    when:
      - eq: 
          a: ${charge_type}
          b: "PREPAID" # 包年包月
    optional: true

  - name: charge_perpaid_auto_renew
    label: 自动续费
    widget: switch
    defaultValue: false
    when:
      - eq: 
          a: ${charge_type}
          b: "PREPAID" # 包年包月
    optional: true

# 前端模块指定
frontend:
  runtimeMode: console
  src: ./software/frontend/console
