kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kafka.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.kafka.image.servicename }}
          image: "{{ .Values.kafka.image.repository }}/{{ .Values.kafka.image.project }}/{{ .Values.kafka.image.servicename }}:{{ .Values.kafka.image.tag  }}"
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_PORT
              value: "{{ .Values.kafka.advertised_port }}"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "{{ .Values.kafka.advertised_host_name }}"
              #value: kafka.default.svc.cluster.local
          ports:
            - name: http
              containerPort: {{ .Values.kafka.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
