apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
  name: kafka-server
spec:
  ports:
  - name: kafka-port
    port: {{ .Values.kafka.service.port }}
    nodePort: {{ .Values.kafka.service.nodePort }}
    targetPort: {{ .Values.kafka.service.targetPort }}
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
  type: {{ .Values.kafka.service.type }}
