kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zookeeper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zookeeper.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.zookeeper.image.servicename }}
          image: "{{ .Values.zookeeper.image.repository }}/{{ .Values.zookeeper.image.project }}/{{ .Values.zookeeper.image.servicename }}:{{ .Values.zookeeper.image.tag  }}"
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.zookeeper.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.zookeeper.resources | nindent 12 }}
