apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: {{ default "zookeeper" .Values.zookeeper.service.labels.app | quote }}
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - port: {{ .Values.zookeeper.service.port }}
      targetPort: {{ .Values.zookeeper.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ default "zookeeper" .Values.zookeeper.service.labels.app | quote }}
