apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kibana.selectorLabels" . | nindent 4 }}
  name: kibana
spec:
  ports:
  - name: http
    port: {{ .Values.kibana.service.port }}
    nodePort: {{ .Values.kibana.service.nodePort }}
    protocol: TCP
    targetPort: {{ .Values.kibana.service.targetPort }}
  selector:
    {{- include "kibana.selectorLabels" . | nindent 4 }}
  type: {{ .Values.kibana.service.type }}
