---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.rabbit.appsName }}
spec: 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.global.storageClass }}
---
