apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "logstash.selectorLabels" . | nindent 4 }}
  name: logstash
spec:
  ports:
  - name: http
    port: {{ .Values.logstash.service.port }}
    protocol: TCP
    targetPort: {{ .Values.logstash.service.targetPort }}
  selector:
    {{- include "logstash.selectorLabels" . | nindent 4 }}
  type: {{ .Values.logstash.service.type }}
